### ISSUE TITLE
Overridden dataset dtype and shape are not passed from parent to child

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#320]
If a schema has two groups, e.g., `PatchClampSeries` and `CurrentClampSeries` defined as such:
```yaml
groups:
- neurodata_type_def: PatchClampSeries
  neurodata_type_inc: TimeSeries
  doc: ...
  datasets:
  - name: data
    dtype: numeric
    dims:
    - num_times
    shape:
    - null
    doc: ...
- neurodata_type_def: CurrentClampSeries
  neurodata_type_inc: PatchClampSeries
  doc: ...
  datasets:
  - name: data
    doc: Recorded voltage.
```
where the `'data'` dataset in `CurrentClampSeries` overrides the `'data'` dataset in the parent `PatchClampSeries`, then the `dtype`, `dims`, and `shape` keys of the parent `PatchClampSeries` `'data'` dataset are not inherited by the child `CurrentClampSeries` `'data'` dataset.

Is this intended behavior? @oruebel @ajtritt 

If so, the NWB schema needs to be amended in a few places.

**Comment by dsleiter** [comment]
I encountered this while doing some validator testing. This also applies when the datasets are defined with specific inheritance, eg:
```
datasets:
- data_type_def: D1
  dtype: numeric
  dims:
  - dim1
  - dim2
  shape:
  - null
  - null
  doc: a base dataset
  attributes:
  - name: foo
    dtype: text
    doc: an attribute
- data_type_def: D2
  data_type_inc: D1
  doc: an inherited dataset
```

Only the attribute `foo` will be validated on a builder for type `D2`. `dtype`, `dims`, and `shape` are not passed down.

It looks like the default inheritance passes down specification elements defined on the dictionary accessible via `BaseStorageSpec.attributes`. However, `DatasetSpec` sets shape, dims, and dtype in the base dict that `ConstructableDict` inherits from (`self['shape']` `self['dims']`, and `self['dtype']` when accessed from within `DatasetSpec`), rather than on the `.attributes` field via `BaseStorageSpec.set_attribute('shape', ...)`, etc.

It looks like the current implementation of #321 treats this by passing down the shape, etc of child attributes when a parent is inherited (e.g. `PatchClampSeries.data.shape` is passed to `CurentClampSeries.data.shape`). However, I'm not sure that would work for the above situation, even if we defined a group holding `D2` as below:

```
groups:
- data_type_def: G1
  doc: a group container
  datasets:
  - name: my_d2
    data_type_def: D2
    doc: a D2 dataset on group G1
```

It looks like #321 might be a bit stale, so maybe a lot has changed between then and hdmf 2.5.1. And I'm not entirely sure I'm clear on how everything is supposed to happen with spec inheritance, so maybe there's something I did wrong with my tests. But it'd be good to validate that #321 does resolve the above situation.
