### ISSUE TITLE
add ability to specify enumerated types

### ISSUE THREAD

**Issue by ajtritt** [hdmf-dev/hdmf#330]
[This](https://github.com/NeurodataWithoutBorders/nwb-schema/pull/425) field in the NWB schema specifies a text field that can take on one of three values. The ability to formally specify these values in the specification will make it possible to validate this field against the specified.

The YAML for this would look something like this:

```YAML
name: <NAME>
dtype: <DTYPE>
enum:                  <--- new argument for a dataset or attribute specification
    - <OPTION_1>
    - <OPTION_2>
    - <OPTION_3>
required: true|false
...
```
(We don't need to use `options` as the key)
