### ISSUE TITLE
Containers in a subgroup can get built twice

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#342]
The schema for `NWBFile` has the named groups `'acquisition'`, `'analysis'`, and `'scratch'`, which each have multiple subgroups defined using `neurodata_type_inc`. For example:
```yaml
  groups:
  - name: acquisition
    groups:
    - neurodata_type_inc: NWBDataInterface
      quantity: '*'
    - neurodata_type_inc: DynamicTable
      quantity: '*'
```

Currently, when the object mapper adds containers for the subgroup specs `NWBDataInterface` and `DynamicTable` to the `GroupBuilder 'acquisition'`, it builds and adds all `Container` objects in `NWBFile.acquisition` for each of the two subgroup specs, regardless of the type. So a `TimeSeries` gets built when processing the `neurodata_type_inc: NWBDataInterface` part of the spec and gets built again when processing `neurodata_type_inc: DynamicTable`.

The object mapper should instead process only the `Container` objects in `NWBFile.acquisition` that match the `neurodata_type_inc` type. 

Note: `NWBFile.acquisition` returns a `LabelledDict` of child `Container` objects.
