### ISSUE TITLE
Cached spec is sometimes not the same as the schema

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#502]
## Description

Related to #501.

If an extension data type, e.g., `data_type_def: FRETSeries` extends an existing type `data_type_inc: ImageSeries` that has attributes, then the extension spec that is cached within a file using this extension will write the inherited attributes as attributes in the new type. 

For example, `FRETSeries` does not define the attribute 'description' but `ImageSeries` does. In the cached extension spec, the attribute spec for 'description' is copied from `ImageSeries` and included in the spec for `FRETSeries` when it should not be. 

This, on its own, has not caused any issues yet, but these attributes are read as overridden attributes rather than inherited attributes in the GroupSpec class, and there may be unintended downstream effects of these attributes being classified incorrectly.

Not to mention, the cached extension spec *should* be a perfect (JSON-translated) copy of the actual extension spec.

## Environment

    Python Executable: Conda
    Python Version: Python 3.8
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
This is true not just for extensions, but for the core schema too. For example in an NWB 2.0.2 file, in the cached spec for `ImageSeries`, the specs for the 'description' and 'comments' attributes are included, but these are not explicitly included in the yaml schema for `ImageSeries`.

**Comment by rly** [comment]
Another example to note: if an extension yaml file has no data types, as it is here:

namespace:
```yaml
- name: hdmf-experimental
  ...
  full_name: HDMF Experimental
  schema:
  - namespace: hdmf-common
  - doc: Experimental data types
    source: experimental.yaml
    title: Experimental data types
  - doc: data types for storing references to web accessible resources
    source: resources.yaml
    title: Resource reference data types
  version: 0.1.0
```
experimental.yaml:
```
groups: []
datasets: []
```
then, the cached spec omits the extension yaml:
```
{'namespaces': [{...,
                 'full_name': 'HDMF Experimental',
                 'name': 'hdmf-experimental',
                 'schema': [{'namespace': 'hdmf-common'},
                            {'source': 'resources'}],
                 'version': '0.1.0'}]}
```

Doc and title are also omitted. (And the source is different but that makes sense because it is referring to the HDF5 group named 'resources' rather than a yaml file.)
