### ISSUE TITLE
Loading namespaces from file with nested extensions fails

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#511]
## Description

Trying to load a file with load_namespaces=True _without_ importing the extension package first, when the extension references another extension, fails with the following error:

Spec from https://github.com/catalystneuro/ndx-ellipse-eye-tracking/blob/master/spec/ndx-ellipse-eye-tracking.extensions.yaml :
```yaml
groups:
- neurodata_type_def: EllipseSeries
  neurodata_type_inc: SpatialSeries
  doc: Information about an ellipse moving over time
  datasets:
  - name: area
    dtype: float
    shape:
    - null
    doc: ellipse area
  - name: width
    dtype: float
    shape:
    - null
    doc: width of ellipse
  - name: height
    dtype: float
    shape:
    - null
    doc: height of ellipse
  - name: angle
    dtype: float
    shape:
    - null
    doc: angle that ellipse is rotated by (phi)
- neurodata_type_def: EllipseEyeTracking
  neurodata_type_inc: EyeTracking
  default_name: EyeTracking
  doc: Stores detailed eye tracking information output from DeepLabCut
  groups:
  - name: eye_tracking
    neurodata_type_inc: EllipseSeries
    doc: eye tracking
  - name: pupil_tracking
    neurodata_type_inc: EllipseSeries
    doc: pupil tracking
  - name: corneal_reflection_tracking
    neurodata_type_inc: EllipseSeries
    doc: corneal reflection tracking
  - name: likely_blink
    neurodata_type_inc: Events
    doc: Indicator of whether there was a probable blink for this frame
```
output:
```
In [2]: io = NWBHDF5IO('/Users/bendichter/dev/ndx/ndx-ellipse-eye-tracking/src/pynwb/tests/test.nwb', mode='r', load_namespaces=True)                                               
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-4b27c2a9ab6d> in <module>
----> 1 io = NWBHDF5IO('/Users/bendichter/dev/ndx/ndx-ellipse-eye-tracking/src/pynwb/tests/test.nwb', mode='r', load_namespaces=True)
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):
~/anaconda3/lib/python3.7/site-packages/pynwb/__init__.py in __init__(self, **kwargs)
    228 
    229             tm = get_type_map()
--> 230             super(NWBHDF5IO, self).load_namespaces(tm, path, file=file_obj)
    231             manager = BuildManager(tm)
    232 
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):
~/anaconda3/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py in load_namespaces(cls, **kwargs)
    118         if file_obj is None:
    119             with File(path, 'r') as f:
--> 120                 return cls.__load_namespaces(namespace_catalog, namespaces, f)
    121         else:
    122             return cls.__load_namespaces(namespace_catalog, namespaces, file_obj)
~/anaconda3/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py in __load_namespaces(cls, namespace_catalog, namespaces, file_obj)
    166         for ns in order:
    167             reader = readers[ns]
--> 168             d.update(namespace_catalog.load_namespaces('namespace', reader=reader))
    169 
    170         return d
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):
~/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py in load_namespaces(self, **kwargs)
    458         load_namespaces here has the advantage of being able to keep track of type dependencies across namespaces.
    459         '''
--> 460         deps = call_docval_func(self.__ns_catalog.load_namespaces, kwargs)
    461         for new_ns, ns_deps in deps.items():
    462             for src_ns, types in ns_deps.items():
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in call_docval_func(func, kwargs)
    421 def call_docval_func(func, kwargs):
    422     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 423     return func(*fargs, **fkwargs)
    424 
    425 
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):
~/anaconda3/lib/python3.7/site-packages/hdmf/spec/namespace.py in load_namespaces(self, **kwargs)
    488         # now load specs into namespace
    489         for ns in to_load:
--> 490             ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
    491         self.__included_specs[ns_path_key] = ret
    492         return ret
~/anaconda3/lib/python3.7/site-packages/hdmf/spec/namespace.py in __load_namespace(self, namespace, reader, types_key, resolve)
    445                     else:
    446                         spec = self.group_spec_cls.build_spec(spec)
--> 447                     catalog.register_spec(spec, spec_file)
    448                 included_types[s['namespace']] = tuple(types)
    449         # construct namespace
~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    578             def func_call(*args, **kwargs):
    579                 pargs = _check_args(args, kwargs)
--> 580                 return func(args[0], **pargs)
    581         else:
    582             def func_call(*args, **kwargs):
~/anaconda3/lib/python3.7/site-packages/hdmf/spec/catalog.py in register_spec(self, **kwargs)
     43         type_name = ndt_def if ndt_def is not None else ndt
     44         if type_name in self.__specs:
---> 45             raise ValueError("'%s' - cannot overwrite existing specification" % type_name)
     46         self.__specs[type_name] = spec
     47         self.__spec_source_files[type_name] = source_file
ValueError: 'Data' - cannot overwrite existing specification
```

## Environment

    Python Executable: Conda
    Python Version: 3.7
    Operating System: Windows, macOS or Linux
    HDMF Version: latest

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
