### ISSUE TITLE
Mismatched fixed name and included name causes errors on read/validate

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#582]
## Description

In HDMF currently, if a container child data type is defined with a fixed name and included as a subgroup of 
some group, and the subgroup is specified with a different name, then after writing to disk, the subgroup keeps the fixed name rather than the subgroup name. The data cannot be read and validation fails. 

Example:
```yaml
groups:
- data_type_def: TypeA
  name: a
- data_type_def: TypeB
  groups:
  - data_type_inc: TypeA
    name: inner_a
```
In HDMF:
```python
a = TypeA()  # a.name = 'a'
b = TypeB(name='b', inner_a=a)
b.inner_a  # returns a and a.name is still 'a'
with HDF5IO('test.h5', 'w') as io:
    io.write(b)  # no errors
with HDF5IO('test.h5', 'r') as io:
    read_b = io.read()  # fails, __init__: missing argument 'inner_a'
# test.h5 has subgroup named 'a'
```

## Environment

    Python Executable: Python
    Python Version: Python 3.8
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
This bug appears when users write NWB extensions and add `name` to both their data type definitions and included type specs, as in https://github.com/akshay-jaggi/ndx-photometry/

**Comment by alessandratrapani** [comment]
In https://github.com/catalystneuro/ndx-holographic-stimulation/pull/7 we are defining new neurodata type following the best practice as in https://github.com/hdmf-dev/hdmf-schema-language/issues/14#:~:text=Use%20the%20name,%C2%A0hdmf%23582
But if we get this error when trying to add a data type with a different name: 
```
ValueError: Field 'site' on PatternedOptogeneticSeries must be named 'site'.
```

Schema:
```yml
- neurodata_type_def: PatternedOptogeneticStimulusSite
  neurodata_type_inc: OptogeneticStimulusSite
  doc: An extension of OptogeneticStimulusSite to include the geometrical representation
    for the stimulus.
  attributes:
  - name: effector
    dtype: text
    doc: Light-activated effector protein expressed by the targeted cell (eg. ChR2)
    required: false
- neurodata_type_def: PatternedOptogeneticSeries
  neurodata_type_inc: TimeSeries
  doc: An extension of OptogeneticSeries to include the spatial patterns for the photostimulation.
  links:
  - doc: link to the patterned stimulus site
    name: site
    target_type: PatternedOptogeneticStimulusSite
```
Example
```python
        stim_site = PatternedOptogeneticStimulusSite(
            name="StimulusSite",
            device=device,
            description=site_description,
            excitation_lambda=stimulation_wavelenght,  # nm
            effector=effector,
            location=location,
        )
        self.nwbfile.add_ogen_site(stim_site)
        photostimulation = PatternedOptogeneticSeries(
            name=series_name,
            description=series_description,
            data=data,
            timestamps=timestamps,
            site=stim_site,
        )
```

The error occurs when using hdmf 3.11.0 and pynwb 2.5.0
