### ISSUE TITLE
LinkSpec without name cannot be written

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf#693]
## Description

When a spec yaml contains:
```yaml
groups:
- neurodata_type_def: A
  doc: ...
  links:
  - target_type: Device
    doc: Cameras used to record the videos.
    quantity: '*'  # this fails with any quantity ('?', '+', 1, '*'), but no name is often associated with quantity '*'
```
And a user provides a device, the following error is raised:
```
AttributeError: 'LinkSpec' object has no attribute 'data_type_def'
..\hdmf\src\hdmf\spec\spec.py:1014: AttributeError
```
## Environment

    Python Executable: Conda
    Python Version: Python 3.9
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the bug was not already [reported](https://github.com/hdmf-dev/hdmf/issues) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
